language: android
android:
  components:
    - platform-tools
    - build-tools-19.1.0
jdk:
  - oraclejdk7
  # - openjdk7

script:
    - echo $ANDROID_HOME
    - find $ANDROID_HOME -name zipalign
    - sudo cp $ANDROID_HOME/build-tools/19.1.0/zipalign /bin/
    - which zip
    - which zipalign
    - which jarsigner
    - echo $user.home
    - ls $user.home
    - cd test
    - bash ./jenkins_test.sh -h
    - cd ..

deploy:
  on:
    all_branches: true