language: android
android:
  components:
    - platform-tools
    - build-tools-19.1.0
jdk:
  - oraclejdk7
  - openjdk7
  
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

cache:
  directories:
    - $HOME/.m2

script:
    - echo $ANDROID_HOME
    - find $ANDROID_HOME -name zipalign
    - sudo cp $ANDROID_HOME/build-tools/19.1.0/zipalign /bin/
    - which zip
    - which zipalign
    - which jarsigner
    - cd test
    - bash ./jenkins_test.sh
    - cd ..
