# see https://www.jenkins.io/redirect/continuous-delivery-of-plugins

name: Publish to Artifactory
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: github.repository_owner == 'jenkinsci'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Build and test
        run: |
          export TF_API_KEY=${{ secrets.TF_API_KEY }}
          echo "CI_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

          set -x

          sed -i "s/4.17.2/${GITHUB_REF#refs/*/}/g" pom.xml
          sed -i "s/-SNAPSHOT//g" pom.xml
          cat pom.xml

          bash scripts/build.sh

          git add .
          git commit -m "Ready for release"
        shell: bash
      - name: Release
        uses: jenkins-infra/jenkins-maven-cd-action@v1.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
